services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    region: singapore
    rootDir: backend   # nếu code nằm trong folder backend
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-backend.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password
      - key: CORS_ALLOWED_ORIGINS
        value: https://wedxemphim4k.vercel.app/